### ISSUE TITLE
(vignette) Describe how to cross-validate with sensitivity and/or specificity

### ISSUE THREAD

**Issue by tpq** [tpq/exprso#15]
Original request as sent by e-mail:

> "When we generate multiple models (as in the setting of calling plMonteCarlo using a grid), can we generate/retain information about SENSITIVITY and SPECIFICITY (within each boot and cross-validation run), and can we later select our "bests" based on plCV-SENSITIVITY (rather than plCV-Accuracy)...?"

**Comment by tpq** [comment]
In reviewing this issue I realize that `plMonteCarlo` (`plMC`) and `plNested` (`plN`) do not calculate the outer-most performance statistics when embedding `plMC` or `plN` within one another. This must get fixed as a corollary to the posted issue.

**Comment by tpq** [comment]
The associated bug is now squashed. However, complete implementation of a "plSensitivity"-like wrapper probably requires creating a new `pl` function altogether. This new function (say, `plNestedConcise`) should function analogously to `plCV`, accomplishing two tasks unambiguously: (a) summarizing performance across *v*-folds, and (b) summarizing performance of the entire training set (think: 1-fold) as deployed on the demi-holdout. Unfortunately, this latter task differs substantially from what is already available in `plNested`.

**Comment by dantylee** [comment]
For future reference:  If you were able to bind "Sens" and "Spec" from CV onto the plMonte => object,  then it would be helpful/important to be able to specify a complex [(2)-filter models] AccBy statement;  the statement would need to be able to assign specific weights to "acc", "sens", "spec".   Otherwise, you'll end up with models that call all subjects case (if selected for sens).

**Comment by tpq** [comment]
This is now handled by the `plCV.acc` argument of the `plGrid` function.
